apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-push-dotnet
  namespace: demo-pipelines
spec:
  serviceAccountName: pipeline
  triggers:
    - name: pushTrigger
      template:
        spec:
          resourceTemplates:
            - apiVersion: tekton.dev/v1beta1
              kind: PipelineRun
              metadata:
                generateName: pipeline-demo-dotnet-run-
              spec:
                pipelineRef:
                  name: pipeline-demo-dotnet
                params:
                  - name: GIT_REPO
                    value: https://github.com/Bunkmate3742/calc

                  - name: GIT_REVISION
                    value: main
                workspaces:
                  - name: source
                    volumeClaimTemplate:
                      spec:
                        accessModes:
                          - ReadWriteOnce
                        resources:
                          requests:
                            storage: 1Gi
                        storageClassName: gp3-csi
                        volumeMode: Filesystem

                  - name: sonarqube-api-token
                    secret:
                      secretName: sonarqube-api-token-calc

